### PR TITLE
Solve "Class 'Composer\Util\Url' not found during project initialization" error

### LINKED ISSUE #28: Class 'Composer\Util\Url' not found during project initialization
As title.

When I try to initialize the new project skeleton, I get this issue.

Here is my setting about this project skeleton:

```
Summary:
--------

 ------------------------------- --------------------- 
  What                            Value                
 ------------------------------- --------------------- 
  Author name                     peter279k            
  Author email                    peter279k@gmail.com  
  Your package                    api-clients/darksky  
  Your project sources location   src/                 
  Your project tests location     tests/               
  Your namespace                  Composer             
  Your test namespace             Composer\Tests       
  Your project namespace          DarkSky              
 ------------------------------- --------------------- 
```

Is the setting wrong?

Please hep me to check that, thanks.

### PR DESCRIPTION
**Pull request by WyriHaximus**
Fixes / Closes #28

### CODE REVIEW

**Comment by peter279k** [comment]
The Travis CI build is failed due to the coding style check.

I think it should be fixed before merging this PR.

**Comment by WyriHaximus** [comment]
@peter279k correct that will be solved. I'm using this branch/PR to to come up with a solution

**Comment by peter279k** [comment]
Hi @WyriHaximus, thank you for your reply.

I will use this for building the new project skeleton again.

**Comment by WyriHaximus** [comment]
Wait for it to be merged, it doesn't work as intended yet :(

**Comment by WyriHaximus** [comment]
Ok the current state solves the issue as described in #28. But I won't solve it here I'll solve it later today somewhere else in the dependency chain

**Pull request merged**
